version: "3.4"

services:
  lil_tim:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
       - TOKEN=${TOKEN:-ADD_TOKEN}
       - PREFIX=${PREFIX:-;;}
       - OWNER_ID=${OWNER_ID:-ADD_OWNER_ID}
       - YOUTUBE_KEY=${YOUTUBE_KEY:-ADD_YOUTUBE_KEY}
       - SPOTIFY_ID=${SPOTIFY_ID:-ADD_SPOTIFY_ID}
       - SPOTIFY_SECRET=${SPOTIFY_SECRET:-ADD_SPOTIFY_SECRET}


